name: Pulumi
on:
  push:
    branches:
      - main
jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1
      
      - name: Setup Pulumi
        uses: pulumi/actions@v4
      
      - name: Apply infrastructure
        run: |
          pulumi stack select McNultyyy/Infrastructure/dev
          pulumi up --cwd Infrastructure --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}